import Header from '@/components/Header'
import { Toaster } from '@/components/ui/toaster'
import Providers from '@/providers'
import fonts from '@/styles/fonts'
import '@/styles/global.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: ReactNode
    authModal?: ReactNode
}

export default function RootLayout({ children, authModal }: RootLayoutProps) {
    return (
        <html lang="en" className={fonts}>
            <body>
                <Providers>
                    {authModal}
                    <Header />
                    {children}
                    {/* <Footer /> */}
                    <Toaster />
                </Providers>
            </body>
        </html>
    )
}
